name:                paper
version:             0.1.0.0
github:              "conal/convolution-paper"
license:             BSD3
author:              "Conal Elliott"
maintainer:          "conal@conal.net"
copyright:           "2018 Conal Elliott"

synopsis:            Language recognition in the spirit of Brzowski's derivatives
category:            language, math

description:         Please see the README on GitHub at <https://github.com/conal/convolution-paper#readme>

library:
  dependencies:
    - base >= 4.7 && < 5
    - ghc-prim
    - data-inttrie
    - containers
    # - distributive
    # - adjunctions
    # - comonad
    # - semiring-num
    # - newtype-generics
  # source-dirs: src
  exposed-modules:
      Code

tests:
  test:
    main:                GoldTests.hs
    source-dirs:         test
    other-modules: []
    dependencies:
    - base
    - Cabal >= 1.24.0.0
    - bytestring
    - tasty
    - tasty-golden
    - paper
