name:                paper
version:             0.1.0.0
github:              "conal/convolution-paper"
license:             BSD3
author:              "Conal Elliott"
maintainer:          "conal@conal.net"
copyright:           "2018 Conal Elliott"

synopsis:            Language recognition in the spirit of Brzowski's derivatives
category:            language, math

description:         Please see the README on GitHub at <https://github.com/conal/convolution-paper#readme>

default-extensions:
  - CPP
  - ConstraintKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - PatternSynonyms
  - QuantifiedConstraints
  - RankNTypes
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - ViewPatterns
  - ScopedTypeVariables

ghc-options: -Wall

cpp-options: -DEXAMPLES

library:
  dependencies:
    - base >= 4.7 && < 5
    - ghc-prim
    - data-inttrie
    - containers
    - multiset
    # - total-map
    # - distributive
    # - adjunctions
    # - comonad
    # - semiring-num
    # - newtype-generics
  other-modules: []
  include-dirs: src
  install-includes: GenInstances.inc
  source-dirs: src
  exposed-modules:
    - Misc
    - Constrained
    - Semi
    # - Map
    # - Language
    # - Decomp
    # - Stream
    - LTrie
    - RegExp
    - Examples
    # To abandon
    # - DLTrie
    # - Convo
    # - CLTrie
    # - Set
    # - Fun

tests:
  test:
    main:                GoldTests.hs
    source-dirs:         test
    other-modules: []
    dependencies:
    - base
    - Cabal >= 1.24.0.0
    - bytestring
    - tasty
    - tasty-golden
    - semiring-num
    - paper

